# QUESTION 1: SOLVING NAIVE BAYES BY HAND

Import the necessary libraries

In [1]:
import pandas as pd

Consider the toy data below which has  10  training examples,  4  binary features indicating presence or absence of the word, and the sentiment associated with each example.

In [2]:
sentiment_toy_data = {
    "predictable": [1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
    "fun": [0, 1, 0, 1, 1, 0, 0, 0, 0, 1],
    "pathetic": [0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
    "satire": [0, 0, 0, 0, 1, 1, 0, 1, 0, 1],
    "target": [
        "negative",
        "positive",
        "negative",
        "positive",
        "positive",
        "negative",
        "positive",
        "negative",
        "negative",
        "negative",
    ],
}

toy_df = pd.DataFrame(sentiment_toy_data)
toy_df

,predictable,fun,pathetic,satire,target
0,1,0,0,0,negative
1,1,1,0,0,positive
2,1,0,1,0,negative
3,0,1,0,0,positive
4,0,1,0,1,positive
5,1,0,1,1,negative
6,1,0,0,0,positive
7,0,0,1,1,negative
8,0,0,1,0,negative
9,1,1,1,1,negative


Given this information, you want to predict the target (positive or negative sentiment) for the following unseen test example:
    
$$x_{new} = \begin{bmatrix}1 & 1 & 0 & 1\end{bmatrix}$$.

## 1.1 Class prior probabilities

{2 marks}

Compute the estimates of the class prior probabilities by hand.
1. Compute $p(\text{positive})$ and store it in a variable called `pos_prior`.
2. Compute $p(\text{negative})$ and store it in a variable called `neg_prior`.

You do not need to show any calculations or provide any explanation. Just compute the raw frequencies/proportions and store them in the respective variables as fractions (e.g., 1/2).

In [3]:
# YOUR ANSWER HERE
pos_prior = (toy_df['target'] == 'positive').mean()
neg_prior = (toy_df['target'] == 'negative').mean()

print(f"Positive Prior: {pos_prior}")
print(f"Negative Prior: {neg_prior}")

Positive Prior: 0.4
Negative Prior: 0.6


## 1.2 Conditional probabilities

{4 marks}

Compute the estimates of the conditional probabilities by hand which are required by naive Bayes for the test example $x_{new}$.
$$x_{new} = \begin{bmatrix}1 & 1 & 0 & 1\end{bmatrix}$$

Store the values of conditional probabilities in the variables below. Each variable represents the probability of presence or absence of the word given the class. For instance, `fun1_pos` represents $p(\text{fun} = 1  \mid \text{positive})$ and `pathetic0_pos` represents $p(\text{pathetic} = 0  \mid \text{positive})$.

You do not need to show any work. Also, do not consider Laplace smoothing here, just compute the raw frequencies/proportions by hand and store them in the respective variables as fractions (e.g., 1/2).

In [ ]:
# YOUR ANSWER HERE
pred1_pos = 1/2
fun1_pos = 3/4
path0_pos = 1/1
sat1_pos = 1/4

pred1_neg = 2/3
fun1_neg = 1/6
path0_neg = 1/6
sat1_neg = 1/2

## 1.3 Prediction

{6 marks}

1. Under the naive Bayes model and your estimates of the above probabilities, what is the most likely label our test example, $x_{new}$: "positive" or "negative"? Show your calculations.

$$x_{new} = \begin{bmatrix}1 & 1 & 0 & 1\end{bmatrix}$$

> I do not expect any code here. Calculate the probabilities by hand. Use formatting of your own choice (e.g., latex preferable).

$$p(\text{positive} \mid predictable = 1, fun = 1, pathetic = 0, satire = 1) = ?$$

$$p(\text{negative} \mid predictable = 1, fun = 1, pathetic = 0, satire = 1) = ?$$

### Answer:

P(positive)=0.4 (or 2/5)

P(pred=1∣pos)=1/2

P(fun=1∣pos)=3/4

P(path=0∣pos)=1

P(sat=1∣pos)=1/4

P(pos)⋅∏P(x 
i
​	
 ∣pos)= 
5
2
​	
 ⋅ 
2
1
​	
 ⋅ 
4
3
​	
 ⋅1⋅ 
4
1
​	
 
= 
5⋅2⋅4⋅1⋅4
2⋅1⋅3⋅1⋅1
​	
 = 
160
6
​	
 =0.0375



 P(negative)=0.6 (or 3/5)

P(pred=1∣neg)=2/3

P(fun=1∣neg)=1/6

P(path=0∣neg)=1/6

P(sat=1∣neg)=1/2

P(neg)⋅∏P(x 
i
​	
 ∣neg)= 
5
3
​	
 ⋅ 
3
2
​	
 ⋅ 
6
1
​	
 ⋅ 
6
1
​	
 ⋅ 
2
1
​	
 
= 
5⋅3⋅6⋅6⋅2
3⋅2⋅1⋅1⋅1
​	
 = 
1080
6
​	
 ≈0.00556

## 1.4 Smoothing

{2 marks}

1. Suppose you are asked to predict sentiment of another new example $\hat{x}_{new}$. What would happen when you try to calculate $p(positive \mid \hat{x}_{new})$? How would you deal with this problem?

$$\hat{x}_{new} = \begin{bmatrix}0 & 1 & 1 & 1\end{bmatrix}$$

> You don't have to write any code here. Just explanation in a few sentences is enough.

### Answer:

In the current model, calculating p(positive∣ new)
 results in a probability of zero. This occurs because the feature pathetic=1 never appears in any "positive" samples in the training data (p(pathetic=1∣positive)=0/4). Since Naive Bayes multiplies all feature probabilities together, a single zero value zeros out the entire product, regardless of how strong the other evidence (like fun=1) might be.

To deal with this problem, we would use Laplace Smoothing

# QUESTION 2: WRITING A NAIVE BAYES CLASSIFIER FROM SCRATCH

Write a class to perform discrete Naive Bayes for a random dataset with n = 1000 (# of data points) and d = 2 (# of dimensions) for a binary classification y [0,1]. x1 and x2 can get any values between [0 and 1]. Then, implement the Laplace Smoothing function for the Naive Bayes class

### Import the necessary libraries

In [ ]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from tqdm import tqdm
from scipy.stats import norm
from sklearn.model_selection import train_test_split

### Creating a sample dataset with two dimensions x1, x2

In [5]:
x1 = np.random.randint(2, size = 1000)
x2 = np.random.randint(2, size = 1000)

y= np.random.randint(2, size = 1000)

### Create an array to store the discrete generated variables x1 and x2

In [6]:
X = np.column_stack((x1, x2))

print(f"Shape of feature matrix X: {X.shape}")
print(f"First 5 rows:\n{X[:5]}")

Shape of feature matrix X: (1000, 2)
First 5 rows:
[[0 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]]


### Create the class for Naive Bayes Classifier

{5 marks}

In [10]:
class Naive_Bayes:

    def __init__(self, X, y, laplace=0):
        self.X = X
        self.y = y
        self.laplace = laplace
        self.priors = {}
        self.likelihoods = {}

    def trainTestSplit(self):
        # Splitting the data into training and testing sets (80/20)
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
            self.X, self.y, test_size=0.2, random_state=42
        )

    def runModel(self):
        # Safeguard: Ensure data is split before training
        if not hasattr(self, 'X_train'):
            self.trainTestSplit()

        # Subsets for class 0 and 1
        X_train_0 = self.X_train[self.y_train == 0]
        X_train_1 = self.X_train[self.y_train == 1]

        # Priors: P(Y=0) and P(Y=1)
        self.priors[0] = len(X_train_0) / len(self.y_train)
        self.priors[1] = len(X_train_1) / len(self.y_train)

        # Likelihoods for binary features (k=2)
        k = self.X_train.shape[1]
        for c, subset in enumerate([X_train_0, X_train_1]):
            self.likelihoods[c] = {}
            for i in range(k):
                # Count instances where feature i == 1
                num_ones = np.sum(subset[:, i] == 1)
                # Apply Laplace smoothing formula
                prob_1 = (num_ones + self.laplace) / (len(subset) + self.laplace * 2)
                self.likelihoods[c][i] = prob_1

    def predict(self):
        # Safeguard: Ensure model is trained before predicting
        if not self.likelihoods:
            self.runModel()

        predictions = []
        for sample in self.X_test:
            posteriors = []
            for c in [0, 1]:
                # Start with the prior
                p_class = self.priors[c]
                # Multiply by conditional probabilities (Likelihoods)
                for i, val in enumerate(sample):
                    p_feat_1 = self.likelihoods[c][i]
                    # If feature is 1, use p_feat_1; if 0, use (1 - p_feat_1)
                    p_class *= p_feat_1 if val == 1 else (1 - p_feat_1)
                posteriors.append(p_class)
            
            # Argmax: index 0 or 1
            predictions.append(np.argmax(posteriors))
            
        return np.array(predictions)

### Execute without Laplace Smooting

{3 marks}

In [11]:
nb = Naive_Bayes(X, y)

In [12]:
nb.runModel()

In [13]:
nb.predict()

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1])

### Execute after Laplace Smooting

{3 marks}

In [14]:
nb = Naive_Bayes(X, y, laplace=1)

In [15]:
nb.runModel()

In [16]:
nb.predict()

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1])

# QUESTION 3: SENTIMENT ANALYSIS WITH NAIVE BAYES

{10 marks}

Perform Sentiment Analysis with the above naive bayes class, on the following dataset: https://www.kaggle.com/datasets/ritresearch/happydb

Follow these steps:


1. Load the dataset: Use the cleaned version of the dataset (cleaned_hm.csv) and load it into a pandas dataframe.
2. Map categories to binary sentiment labels:
  * Categories affection and exercise should be labeled as happy (1).
  * All other categories should be labeled as not_happy (0).
3. Select the required columns: Extract the columns containing the text data and the binary sentiment labels.
4. Split the data into training and testing sets:
  * Use an 80-20 train-test split.
  * Ensure random_state is set for reproducibility.
5. Convert text data into numerical vectors:
  * Use the CountVectorizer from scikit-learn to create feature vectors.
  * Fit the CountVectorizer on the training data and transform both training and testing data.
6. Train a Naive Bayes classifier:
  * Instantiate the Naive Bayes class and train it on the training data.
7. Evaluate the model:
  * Predict the sentiment on the test data.
  * Calculate the accuracy score and generate a classification report.

### Import necessary libraries

In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report
import requests
from zipfile import ZipFile
import io

### Load the dataset into a dataframe

Download dataset and load it into your google colab from: https://www.kaggle.com/datasets/ritresearch/happydb

In [18]:
df = pd.read_csv('/Users/wilco/DAE Projects/7300 Test/wk9 Naive Bayes in Practice/cleaned_hm.csv')

In [20]:
# Map the 'ground_truth_category' into binary sentiment

df_filtered = df.dropna(subset=['ground_truth_category']).copy()

happy_categories = ['affection', 'exercise']
df_filtered['label'] = df_filtered['ground_truth_category'].isin(happy_categories).astype(int)

# Assuming 'affection' and 'exercise' are considered happy (label 1)
# Map other categories to 'not_happy' (label 0)

vectorizer = CountVectorizer(binary=True, stop_words='english', max_features=1000)
X = vectorizer.fit_transform(df_filtered['cleaned_hm']).toarray()
y = df_filtered['label'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
# Select the required columns

df = df[['cleaned_hm', 'ground_truth_category']]

In [23]:
# Split data into features (X) and labels (y)

df = df[df['ground_truth_category'].notnull()].copy()

happy_categories = ['affection', 'exercise']
df['label'] = df['ground_truth_category'].apply(lambda x: 1 if x in happy_categories else 0)

X = df['cleaned_hm']
y = df['label']

print(f"Total samples: {len(y)}")
print(f"Happy samples (1): {sum(y == 1)}")
print(f"Not Happy samples (0): {sum(y == 0)}")

Total samples: 14125
Happy samples (1): 5027
Not Happy samples (0): 9098


In [26]:
# Convert text data to numerical vectors using CountVectorizer

vectorizer = CountVectorizer(binary=True, stop_words='english', max_features=1000)

X = vectorizer.fit_transform(df['cleaned_hm']).toarray()

y = df['label'].values

print(f"Feature matrix shape: {X.shape}")

Feature matrix shape: (14125, 1000)


In [27]:
# Instantiate the Naive_Bayes class

nb_model = Naive_Bayes(X, y, laplace=1)

In [28]:
# Train the model
nb.runModel()

In [29]:
# Predict on the test data
nb.predict()

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1])